version: "3.7"
services:
  test:
    build:
      dockerfile: Dockerfile.test
      context: .
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: 'postgres://bridge:bridge@postgres:5432'
      REDIS_URL: 'redis://redis:6379/1'
    command: sh -c "docker/bin/run-tests.sh"
    volumes:
      - type: bind
        source: ./log
        target: /usr/src/app/log
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  postgres: &db
    image: postgres:9.5
    environment:
      POSTGRES_USER: bridge
      POSTGRES_PASSWORD: bridge
    ports:
      - "${DB_PORT_MAP:-5432}"
  redis: &redis
    image: redis:5.0-alpine
    ports:
      - "6379"
