#! /bin/sh

export AKS_RESOURCE_GROUP=bridge-staging
export AKS_CLUSTER_NAME=bridge-k8s-staging
export ACR_RESOURCE_GROUP=bridge
export ACR_NAME=bridgepurchasing
ACR_ID=$(az acr show --name $ACR_NAME --resource-group $ACR_RESOURCE_GROUP --query "id" --output tsv)
CLIENT_ID=$(az aks show --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --query "servicePrincipalProfile.clientId" --output tsv)
az role assignment create --assignee $CLIENT_ID --role acrpull --scope $ACR_ID