apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - bridgevision-preprod.eastus.cloudapp.azure.com
  - bridgepreprod.metova.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - bridgevision-preprod.eastus.cloudapp.azure.com
      - bridgepreprod.metova.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer